name: CI
on:
  push:
    branches:
      - '**'  # This will run on any branch
  pull_request:
    branches:
      - '**'  # This will run on PRs targeting any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Copy Environment File
        run: cp .env.example .env
        
      - name: Build Home Service
        run: |
          cd backend/home-service
          go mod tidy
          go build -v ./...
          
      - name: Build Room Service
        run: |
          cd backend/room-service
          go mod tidy
          go build -v ./...
          
      - name: Build Object Service
        run: |
          cd backend/object-service
          go mod tidy
          go build -v ./...
          
      - name: Build User Service
        run: |
          cd backend/user-service
          go mod tidy
          go build -v ./...
          
      - name: Build Docker Images
        run: docker compose build
        
      - name: Run Tests
        run: |
          cd backend/home-service && go test ./... -v
          cd ../room-service && go test ./... -v
          cd ../object-service && go test ./... -v
          cd ../user-service && go test ./... -v
          
      - name: Check Docker Compose
        run: docker compose config
        
      - name: Report Status
        run: |
          echo "Build completed on branch ${GITHUB_REF#refs/heads/}"
          echo "Commit SHA: $GITHUB_SHA"